### ISSUE TITLE
Uncaught TypeError on data array event attachment

### ISSUE THREAD

**Issue by lmartins** [ripplejs/ripple#24]
When trying to attach the `change` event to a data array, I get the following error:
`Uncaught TypeError: undefined is not a function`

You can see the problem in jsfiddle:
http://jsfiddle.net/lmartins/VPB93/

**Comment by anthonyshort** [comment]
In this case, use ready instead of created. When ready is called, everything is bound and the array should have been transformed

**Comment by anthonyshort** [comment]
```
CustomSMS.ready(function(){
  // etc
});
```

**Comment by lmartins** [comment]
Thanks Anthony.
