### ISSUE TITLE
Example setup without using Component

### ISSUE THREAD

**Issue by goliatone** [ripplejs/ripple#29]
It would be rather useful to see a working example without using component. I am considering using ripple in my current project- which uses requirejs to manage modules.
Else, if I get some guidance I could eventually do this myself and submit a PR.

**Comment by anthonyshort** [comment]
I'm not sure I'm going to look at supporting anything other than Component and Browserify at the moment. It is exports with AMD's define too: https://github.com/ripplejs/ripple/blob/master/dist/ripple.js#L2755 

So you should just be able to load that as normal if you download the standalone version.

**Comment by anthonyshort** [comment]
I also haven't used requirejs in a few years so I wouldn't be the best person to write an example. If you can get it working and want to write something up I'd be happy to add it to the docs.

**Comment by goliatone** [comment]
The real issue for me is the number of dependencies- plugins and plugin dependencies. 
If you build the markdown-editor example, there are 28 or so dependencies. 
Well, the path of least resistance took me to [ractivejs](http://ractivejs.org).
Thanks!

**Comment by anthonyshort** [comment]
Yeah ripple is built for package managers :)
