### ISSUE TITLE
how does data flow to children? 

### ISSUE THREAD

**Issue by matthewmueller** [ripplejs/ripple#35]
Starting to play with ripple and reading the composition docs. It says that the parents pass the data to the children. I'm a bit confused on what you give the parents to render the children correctly. Is it an array of objects? Example:

``` js
[
  {
    username: "anthony",
    ...
  },
  {
    username: "matt",
    ...
  }
]
```

**Comment by anthonyshort** [comment]
Do you mean iteration or just sending data to children?

When you compose another view like `.compose('foo', MyView)` you use it in your templates like a custom element.

```
<foo></foo>
```

It'll just create an instance of `MyView` and replace that element. Then you can send data and keep it in sync using attributes

```
<foo name="{{bar}}"></foo>
```

This will set the `name` property of the `MyView` instance to whatever the `bar` value is on the parent.

It's really just an abstraction so you don't need to create sub-views in the class and the render them yourself and keep properties in sync.

For lists of views things are a bit trickier. I'm working on [this plugin](https://github.com/ripplejs/list) to make it easier or there's the [each plugin](https://github.com/ripplejs/each) for that. The second one just creates views for you on the fly using the template.

**Comment by anthonyshort** [comment]
https://github.com/ripplejs/ripple/blob/master/lib/bindings/child.js#L22 

In the child-binding that's where it's send through the data. That's the binding that handles the "custom" elements and keeps properties in sync between the parent and child.

**Comment by matthewmueller** [comment]
Ahh yup, that answers my question. I was wondering about how ripple would render lists or any one-to-many view relationship. Thanks!

**Comment by anthonyshort** [comment]
No probs, lists are a pain in the ass. I want to try and avoid as much magic as possible for them as well.

**Comment by matthewmueller** [comment]
hahaha yah.. i've spent too much time thinking about list views. they're awful. sounds good though!
